# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 22:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zmessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
