# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zmessages', '0002_auto_20170527_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='msg',
        ),
    ]
