# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmessages', '0005_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
